title: Accessibilty Scouts Camp
author:
  name: Kyle Bacon
  email: 'hello@kylebaconcreative.com'
metadata:
    description: 'Learn how to make the web accessible for those with vision, sound, and interactive disabilities. Earn badges as you learn!'
